#!/usr/bin/env python3

import html
import json
import sys
from datetime import datetime, timezone


def main() -> None:
    payload = json.load(sys.stdin)
    inputs = payload.get("inputs", {})

    draft = inputs.get("draft_news_brief", {}) or {}
    draft_content = (draft.get("content", "") or "").strip()
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    if not draft_content:
        raise SystemExit("draft_news_brief.content was empty")

    human_date = generated_at.split(" ")[0]
    subject = f"AI News Intelligence Brief - {human_date}"

    footer = (
        "\n\n---\n"
        f"Generated by Acsa at {generated_at}."
    )

    markdown = draft_content + footer
    body_html = (
        "<html><body style=\"font-family:Arial,sans-serif;line-height:1.5;white-space:pre-wrap\">"
        + html.escape(markdown)
        + "</body></html>"
    )
    json.dump(
        {
            "body": markdown,
            "body_html": body_html,
            "markdown": markdown,
            "subject": subject,
        },
        sys.stdout,
    )


if __name__ == "__main__":
    main()
